version: '3.8'

services:
  api:
    volumes:
      - ./api:/app/api
    environment:
      - DEBUG=True
    ports:
      - "5000:5000"
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000", "--debug"]

  celery-worker:
    volumes:
      - ./api:/app/api
    environment:
      - DEBUG=True

  celery-beat:
    volumes:
      - ./api:/app/api
    environment:
      - DEBUG=True

  nginx:
    volumes:
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf

  redis:
    ports:
      - "6379:6379" 