version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: neurolibre-postgres
    environment:
      POSTGRES_USER: neurolibre
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: neurolibre
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U neurolibre"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: